# Generated by Django 4.2.3 on 2023-07-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('credit', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numer', models.CharField(default=None, max_length=11)),
                ('operation', models.IntegerField(choices=[(0, 'credit_withdrawal'), (1, 'increase_credit')])),
                ('operation_time', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='credit_sale.seller')),
            ],
            options={
                'ordering': ['operation_time'],
            },
        ),
    ]
