# Generated by Django 4.2.3 on 2023-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_sale', '0002_alter_seller_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
