# Generated by Django 4.2.3 on 2023-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_sale', '0003_rename_phone_numer_operation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
